NDefines.NCountry.LOCAL_MANPOWER_ACCESSIBLE_NON_CORE_FACTOR = 0.25; 
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 1500;					
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 1500;
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 1500;
NDefines.NMilitary.BASE_CAPTURE_EQUIPMENT_RATIO = 0.05;

NDefines.NMilitary.NEW_COMMANDER_RANDOM_PERSONALITY_TRAIT_CHANCES = { 0.95, 0.50, 0.35, 0.10 };